### ISSUE TITLE
Hola mundo - Android

### ISSUE THREAD

**Issue by vicboma1** [kotlin-es/kotlin-es.github.io#4]
Hacer un pequeño proyecto para utilizar Kotlin en Android.

**Comment by vicboma1** [comment]
Introducción
Construcción del proyecto
Migrar a Kotlin 
Lanzar App con el emulador.

**Comment by vicboma1** [comment]
He hecho un Fork para trabajar desde local.
La noticia aún no está acabada pero se puede ver aquí.
https://github.com/vicboma1/kotlin-es.github.io/blob/master/_posts/articles/2015-11-22-android-hello-world.markdown

He descrito el proyecto para iniciados. Están los N pasos detallados.
Falta acabar, revisar y madurar la noticia. 
También falta añadir el repo.

**Comment by soywiz** [comment]
También si quieres hay una carpeta llamada _drafts. Y levantando "jekyll s --drafts" debería sacarte los drafts en teoría y github no los mete. Y además los archivos de draft no necesitan fecha. Se suele trabajar ahí hasta que esté ya rulando y luego cuando se va a publicar se le pone ya la fecha.

**Comment by vicboma1** [comment]
Vale, muchas gracias Carlos.
Desconocía la utilización de esa carpeta (todo sea dicho xD)
Haber si tengo tiempo a la noche y miro un problemilla que tengo porque lanzo el "hola mundo" en dispositivo tablet y me va. Lo lanzo en el Z2 y... "desafortunadamente la aplicación ha dejado de funcionar" ... LOL

**Comment by vicboma1** [comment]
Operativa para lectura https://github.com/vicboma1/kotlin-es.github.io/blob/master/_posts/articles/2015-11-22-android-hello-world.markdown
