### ISSUE TITLE
Problema con arrículo con contenido indivisible en móvil

### ISSUE THREAD

**Issue by soywiz** [kotlin-es/kotlin-es.github.io#5]
![image](https://cloud.githubusercontent.com/assets/570848/11320529/41c3737e-909b-11e5-9219-1f650188c594.png)

En artículos con enlaces largos, como los enlaces delfinal del artículo de tailcall recursion, sale el ancho de la página fastidiado. Hay que añadir un overflow: hidden al div con el contenido del artículo para arreglarlo.

**Comment by soywiz** [comment]
Arreglado

**Comment by vicboma1** [comment]
Ok!
