### ISSUE TITLE
Arreglar apartado de Referencias - Tail Call Optimization

### ISSUE THREAD

**Issue by vicboma1** [kotlin-es/kotlin-es.github.io#6]
Se visualiza esto:
Stack (abstract data type), [https://en.wikipedia.org/wiki/Stack(abstract_data_type)](https://en.wikipedia.org/wiki/Stack(abstract_data_type)){:target=”_blank”} 

Hay un ')' de más.

**Comment by vicboma1** [comment]
He comprimdo la url para que sea más pequeña.

**Comment by soywiz** [comment]
@vicboma1 si colocas #6 en la descripción del commit, sale referenciado aquí el commit y se puede ver mientras lees la tarea.

**Comment by vicboma1** [comment]
Vale, eso no lo sabía. Apuntado!
